/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl_csdl;

import Chung.Connect;
import Chung.SetCursor;
import GiamDoc.QuanLy1;
import NhanVien.QuanLy;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author trieu_000
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Connection con;
    private PreparedStatement stmt;//thuc hien cau truy van
    private ResultSet result;//nhan ket qua truy van

    BacSi bs;
    QuanLy ql;
    QuanLy1 gd;

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);//set frame chinh giua man hinh
        con = new Connect().connect();
        new SetCursor().setCusor(this);
    }

    private void checkID() {
        String pw = new String(jPasswordField.getPassword());
//        String sql = new String("SELECT * FROM \"NhanVien\" WHERE \"IDNV\" =" + tfUserName.getText().trim() + "AND \"Password\" =" + pw.trim());
        String sql = "SELECT * FROM \"NhanVien\" WHERE lower(\"IDNV\") = ? AND lower(\"Password\") = ?";
        //  GD0001
        //  123456
        try {
            stmt = con.prepareStatement(sql);
            stmt.setString(1, tfUserName.getText().trim().toLowerCase());
            stmt.setString(2, pw.trim().toLowerCase());
            System.out.println(sql);

            result = stmt.executeQuery();
            if (result.next()) {
                if (result.getString("IDNV").isEmpty() == false
                        && result.getString("Password").isEmpty() == false) {
                    System.out.println("ID: " + tfUserName.getText());
                    System.out.println("Password: " + pw);
                    if (result.getString("ChucVu").trim().equals("Bác Sĩ") == true) {//vao Frame BacSi
                        setVisible(false);
                        bs = new BacSi(result.getString("IDNV").trim());
                    } else if (result.getString("ChucVu").trim().equals("Nhân Viên") == true) {//vao Frame Quan Ly
                        setVisible(false);
                        ql = new QuanLy(result.getString("IDNV").trim());
                    } else if (result.getString("ChucVu").trim().equals("Giám Đốc") == true) {//vao Frame Giam Doc
                        setVisible(false);
                        gd = new QuanLy1(result.getString("IDNV").trim());
                    }
                }
            } else {
//                System.out.println("ID hoặc password bị sai");
                JOptionPane.showMessageDialog(null, "ID hoặc password bị sai");
            }
            result.close();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUserName = new javax.swing.JTextField();
        bLogin = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        cbShow = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);

        tfUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfUserName.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tfUserNameMouseMoved(evt);
            }
        });
        tfUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUserNameKeyPressed(evt);
            }
        });

        bLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bLogin.setText("Login");
        bLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bLoginFocusLost(evt);
            }
        });
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        bLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bLoginKeyPressed(evt);
            }
        });

        jPasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyPressed(evt);
            }
        });

        cbShow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbShow.setText("Show Password");
        cbShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowActionPerformed(evt);
            }
        });
        cbShow.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbShowKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("User ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfUserName, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbShow))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jPasswordField, tfUserName});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUserNameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfUserNameMouseMoved
        String pw = new String(jPasswordField.getPassword());
        if (pw.equals("") == true) {
            tfUserName.requestFocusInWindow();
        }
    }//GEN-LAST:event_tfUserNameMouseMoved


    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        checkID();
    }//GEN-LAST:event_bLoginActionPerformed

    private void tfUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUserNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jPasswordField.requestFocusInWindow();
            jPasswordField.selectAll();
        } else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            jPasswordField.requestFocusInWindow();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            jPasswordField.requestFocusInWindow();
        }
    }//GEN-LAST:event_tfUserNameKeyPressed


    private void bLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            checkID();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            jPasswordField.requestFocusInWindow();
        } else if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            cbShow.requestFocusInWindow();
        }
    }//GEN-LAST:event_bLoginKeyPressed

    private void jPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            checkID();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tfUserName.requestFocusInWindow();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            bLogin.requestFocusInWindow();
        }
    }//GEN-LAST:event_jPasswordFieldKeyPressed

    private void cbShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowActionPerformed
        if (cbShow.isSelected()) {
            jPasswordField.setEchoChar((char) 0);
            System.out.println(jPasswordField.getText());
        } else {
            jPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_cbShowActionPerformed

    private void cbShowKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbShowKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cbShow.doClick();
        }
    }//GEN-LAST:event_cbShowKeyPressed

    private void bLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bLoginFocusGained
        bLogin.setBackground(Color.GRAY);
        bLogin.setForeground(Color.WHITE);
    }//GEN-LAST:event_bLoginFocusGained

    private void bLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bLoginFocusLost
        bLogin.setBackground(Color.LIGHT_GRAY);
        bLogin.setForeground(Color.BLACK);
    }//GEN-LAST:event_bLoginFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JCheckBox cbShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables
}
