/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NhanVien;

import Chung.Connect;
import Chung.SetCursor;
import NhanVien.QuanLy;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronaldo Hanh
 */
public class ThemBenhNhan extends javax.swing.JFrame {

    /**
     * Creates new form ThemBenhNhan
     */
    private Connection con;
    private PreparedStatement stmt1;
    private PreparedStatement stmt;
    private ResultSet rs;
    private String Nam;
    private String Thang;
    private String Ngay;
    private String gioiTinh;
    private String theBaoHiem;
    private Date date;

    QuanLy PreObject;

    public ThemBenhNhan() {
    }

    public ThemBenhNhan(Object PreObject) {
        if (!(PreObject instanceof QuanLy)) {
            JOptionPane.showMessageDialog(null, "WARNING: ThemBenhNhan. PreObject != QuanLy");
        }
        this.PreObject = (QuanLy) PreObject;
        con = new Connect().connect();
        initComponents();
        
        this.setLocationRelativeTo(null);
        loadTen();
        new SetCursor().setCusor(this);
        setComboboxNam();
        setComBoboxNgay();
        setComBoboxThang();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void loadTen() {
        jLabel2.setText("Xin chào nhân viên mã: " + PreObject.getIDQL());
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbMaBenhNhan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfMaBenhNhan = new javax.swing.JTextField();
        tfHoTen = new javax.swing.JTextField();
        tfDiaChi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbbGioiTinh = new javax.swing.JComboBox();
        cbbTheBaoHiem = new javax.swing.JComboBox();
        cbbThang = new javax.swing.JComboBox();
        cbbNam = new javax.swing.JComboBox();
        cbbNgay = new javax.swing.JComboBox();
        btThem = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm bệnh nhân");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm Bệnh Nhân");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbMaBenhNhan.setText("Mã bệnh nhân");

        jLabel5.setText("Họ và tên");

        jLabel6.setText("Ngày sinh");

        jLabel7.setText("Địa chỉ");

        jLabel8.setText("Giới tính");

        tfMaBenhNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaBenhNhanActionPerformed(evt);
            }
        });
        tfMaBenhNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMaBenhNhanKeyPressed(evt);
            }
        });

        tfHoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfHoTenKeyPressed(evt);
            }
        });

        tfDiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDiaChiKeyPressed(evt);
            }
        });

        jLabel4.setText("Thẻ bảo hiểm y tế");

        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));
        cbbGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbGioiTinhActionPerformed(evt);
            }
        });
        cbbGioiTinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbbGioiTinhKeyPressed(evt);
            }
        });

        cbbTheBaoHiem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Có", "Không" }));
        cbbTheBaoHiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbbTheBaoHiemKeyPressed(evt);
            }
        });

        cbbThang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbbThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThangActionPerformed(evt);
            }
        });
        cbbThang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbbThangKeyPressed(evt);
            }
        });

        cbbNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNamActionPerformed(evt);
            }
        });
        cbbNam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbbNamKeyPressed(evt);
            }
        });

        cbbNgay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbbNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNgayActionPerformed(evt);
            }
        });
        cbbNgay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbbNgayKeyPressed(evt);
            }
        });

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        btThem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btThemKeyPressed(evt);
            }
        });

        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });
        btThoat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btThoatKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(lbMaBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfMaBenhNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                        .addComponent(tfHoTen))
                                    .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 8, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbGioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbTheBaoHiem, 0, 77, Short.MAX_VALUE))))
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btThoat)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, lbMaBenhNhan});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbbNam, cbbNgay, cbbThang});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btThem, btThoat});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMaBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMaBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(cbbNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbTheBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThoat))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbbGioiTinh, cbbTheBaoHiem, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, lbMaBenhNhan, tfDiaChi, tfHoTen, tfMaBenhNhan});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbbNam, cbbNgay, cbbThang});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btThem, btThoat});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfMaBenhNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaBenhNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaBenhNhanActionPerformed

    private void cbbGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbGioiTinhActionPerformed

    private void cbbThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbThangActionPerformed

    private void cbbNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbNamActionPerformed
    private void hamThemBenhNhan() {
        if ((tfMaBenhNhan.getText().equals("")) || (tfDiaChi.getText().equals("")) || (tfHoTen.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Bạn phải nhập đầy đủ thông tin của bệnh nhân. Hãy kiểm tra lại.");
        } else {
            String sql = "insert into \"BenhNhan\" (\"IDBN\",\"Ten\", \"NgaySinh\", \"GioiTinh\", \"DiaChi\", \"isBHYT\",\"Tuoi\") values(?,?,?,?,?,?,?)";
            Nam = cbbNam.getSelectedItem().toString();
            Thang = cbbThang.getSelectedItem().toString();
            Ngay = cbbNgay.getSelectedItem().toString();
            theBaoHiem = cbbTheBaoHiem.getSelectedItem().toString();
            gioiTinh = cbbGioiTinh.getSelectedItem().toString();

            String ngaySinh = Nam + "-" + Thang + "-" + Ngay;

            //System.out.println(ngaySinh);
            date = Date.valueOf(ngaySinh);
            int Tuoi = 2016 - Integer.parseInt(Nam);
            /*SimpleDateFormat sdf=new SimpleDateFormat("ddMMyyyy");
         
        
             try {
             date = (Date) sdf.parse(ngaySinh);
             } catch (ParseException ex) {
             Logger.getLogger(ThemBenhNhan.class.getName()).log(Level.SEVERE, null, ex);
             }
             java.sql.Date sql1 = new java.sql.Date(date.getTime());*/
            try {
                stmt = con.prepareStatement(sql);
                stmt.setString(1, tfMaBenhNhan.getText());
                stmt.setString(2, tfHoTen.getText());
                stmt.setDate(3, date);
                if (gioiTinh.equals("Nam")) {
                    stmt.setInt(4, 1);
                } else {
                    stmt.setInt(4, 0);
                }
                if (theBaoHiem.equals("Có")) {
                    stmt.setInt(6, 1);
                } else {
                    stmt.setInt(6, 0);
                }
                //stmt.setString(4, gioiTinh);
                stmt.setString(5, tfDiaChi.getText());
                //stmt.setString(6, theBaoHiem);
                stmt.setInt(7, Tuoi);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Đã thêm!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Mã số bệnh nhân đã tồn tại. Hãy kiểm tra lại");
                tfMaBenhNhan.requestFocus();
            }
              try {
                String sql1 = "insert into \"BenhAn\"(\"IDBN\",\"GhiChu\") values(?,' ')";
                stmt1 = con.prepareStatement(sql1);
                stmt1.setString(1, tfMaBenhNhan.getText());
                stmt1.executeUpdate();
            } catch (Exception e) {
                System.out.println(e.toString());
            }
        }

    }
    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        hamThemBenhNhan();
    }//GEN-LAST:event_btThemActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        PreObject.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btThoatActionPerformed

    private void tfMaBenhNhanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMaBenhNhanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tfHoTen.requestFocus();
        }
    }//GEN-LAST:event_tfMaBenhNhanKeyPressed

    private void tfHoTenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHoTenKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            //cbbNgay.requestFocus();
            tfDiaChi.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tfMaBenhNhan.requestFocus();
        }
    }//GEN-LAST:event_tfHoTenKeyPressed

    private void cbbNgayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbbNgayKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            //cbbNgay.transferFocus();
            //tfDiaChi.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tfHoTen.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            cbbThang.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_LEFT) {

        }
    }//GEN-LAST:event_cbbNgayKeyPressed

    private void cbbThangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbbThangKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tfDiaChi.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tfHoTen.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            cbbNam.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            cbbNgay.requestFocus();
        }
    }//GEN-LAST:event_cbbThangKeyPressed

    private void cbbNamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbbNamKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tfDiaChi.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tfHoTen.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {

        } else if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            cbbThang.requestFocus();
        }
    }//GEN-LAST:event_cbbNamKeyPressed

    private void tfDiaChiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDiaChiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            cbbGioiTinh.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            cbbNgay.requestFocus();
        }
    }//GEN-LAST:event_tfDiaChiKeyPressed

    private void cbbGioiTinhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbbGioiTinhKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            cbbTheBaoHiem.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tfDiaChi.requestFocus();
        }
    }//GEN-LAST:event_cbbGioiTinhKeyPressed

    private void cbbTheBaoHiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbbTheBaoHiemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btThem.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            cbbGioiTinh.requestFocus();
        }
    }//GEN-LAST:event_cbbTheBaoHiemKeyPressed

    private void btThemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btThemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tfMaBenhNhan.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            cbbGioiTinh.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            btThoat.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            hamThemBenhNhan();
        }
    }//GEN-LAST:event_btThemKeyPressed

    private void btThoatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btThoatKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tfMaBenhNhan.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            cbbGioiTinh.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            btThem.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            QuanLy ql = new QuanLy();
            this.setVisible(false);
            ql.setVisible(true);
        }
    }//GEN-LAST:event_btThoatKeyPressed

    private void cbbNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbNgayActionPerformed
    private void setComboboxNam() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        int i;
        for (i = 1900; i <= 2017; i++) {
            model.addElement(i);
        }
        cbbNam.setModel(model);
    }

    private void setComBoboxNgay() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        int i;
        for (i = 1; i <= 31; i++) {
            model.addElement(i);
        }
        cbbNgay.setModel(model);
    }

    private void setComBoboxThang() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        int i;
        for (i = 1; i <= 12; i++) {
            model.addElement(i);
        }
        cbbThang.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemBenhNhan("NV0001").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThoat;
    private javax.swing.JComboBox cbbGioiTinh;
    private javax.swing.JComboBox cbbNam;
    private javax.swing.JComboBox cbbNgay;
    private javax.swing.JComboBox cbbThang;
    private javax.swing.JComboBox cbbTheBaoHiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbMaBenhNhan;
    private javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfHoTen;
    private javax.swing.JTextField tfMaBenhNhan;
    // End of variables declaration//GEN-END:variables
}
