/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NhanVien;

import Chung.Connect;
import Chung.SetCursor;
import NhanVien.QuanLy;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ronaldo Hanh
 */
public class TimThongTinBenhNhan extends javax.swing.JFrame {

    /**
     * Creates new form TimThongTinBenhNhan
     */
    private Connection con;
    private PreparedStatement stmt;
    private ResultSet rs;
    private 

    String IDQL;
    
    Object PreObject;

    public TimThongTinBenhNhan() {
    }

    public TimThongTinBenhNhan(Object PreObject) {
        this.PreObject = PreObject;
        con = new Connect().connect();

        initComponents();
        this.setLocationRelativeTo(null);
        new SetCursor().setCusor(this);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfMaSoBenhNhan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfHoTen = new javax.swing.JTextField();
        btTimKiem = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBenhNhan = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tìm thông tin bệnh nhân");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông Tin Bệnh Nhân");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mã số bệnh nhân");

        tfMaSoBenhNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaSoBenhNhanActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Họ và tên");

        btTimKiem.setText("Tìm Kiếm");
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });

        jButton1.setText("Hiển thị thông tin của tất cả bệnh nhân");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbBenhNhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã số bệnh nhân", "Họ và tên", "Ngày sinh", "Giới tính", "Địa chỉ", "Thẻ bảo hiểm y tế", "Tuổi"
            }
        ));
        jScrollPane1.setViewportView(tbBenhNhan);

        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMaSoBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btTimKiem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btTimKiem, jButton1, jButton2});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMaSoBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(tfHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btTimKiem, jButton1, jButton2, jLabel2, jLabel3, tfHoTen, tfMaSoBenhNhan});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void showBenhNhan() {
        Vector columnName = new Vector();
        columnName.add("Mã số bệnh nhân");
        columnName.add("Họ và tên");
        columnName.add("Ngày sinh");
        columnName.add("Giới tính");
        columnName.add("Địa chỉ");
        columnName.add("Thẻ bảo hiểm y tế");
        columnName.add("Tuổi");
        Vector data = new Vector();

        if (tfHoTen.getText().equals("") && !tfMaSoBenhNhan.getText().equals("")) {
            String sql = "Select * from \"BenhNhan\" where lower(\"IDBN\")=?";
            try {
                stmt = con.prepareStatement(sql);
                stmt.setString(1, tfMaSoBenhNhan.getText().toLowerCase().trim());
                rs = stmt.executeQuery();
                boolean check = false;
                while (rs.next()) {
                    check = true;
                    Vector user = new Vector();
                    user.addElement(rs.getString(1));
                    user.addElement(rs.getString(2));
                    user.addElement(rs.getDate(3));
                    if (rs.getInt(4) == 1) {
                        user.addElement("Nam");
                    } else {
                        user.addElement("Nữ");
                    }

                    user.addElement(rs.getString(5));
                    if (rs.getInt(6) == 1) {
                        user.addElement("Có");
                    } else {
                        user.addElement("Không");
                    }
                    user.addElement(rs.getInt(7));
                    data.add(user);
                }
                if (check == false) {
                    JOptionPane.showMessageDialog(null, "Không tồn tại mã số bệnh nhân");
                }
            } catch (Exception e) {
            }
            tbBenhNhan.setModel(new DefaultTableModel(data, columnName));
        } else if (tfMaSoBenhNhan.getText().equals("") && !tfHoTen.getText().equals("")) {
            String sql = "Select * from \"BenhNhan\" where lower(\"Ten\")=?";
            try {
                stmt = con.prepareStatement(sql);
                stmt.setString(1, tfHoTen.getText().toLowerCase().trim());
                rs = stmt.executeQuery();
                boolean check = false;
                while (rs.next()) {
                    check = true;
                    Vector user = new Vector();
                    user.addElement(rs.getString(1));
                    user.addElement(rs.getString(2));
                    user.addElement(rs.getDate(3));
                    if (rs.getInt(4) == 1) {
                        user.addElement("Nam");
                    } else {
                        user.addElement("Nữ");
                    }

                    user.addElement(rs.getString(5));
                    if (rs.getInt(6) == 1) {
                        user.addElement("Có");
                    } else {
                        user.addElement("Không");
                    }
                    user.addElement(rs.getInt(7));
                    data.add(user);
                }
                if (check == false) {
                    JOptionPane.showMessageDialog(null, "Không tồn tại  bệnh nhân");
                }
            } catch (Exception e) {
                System.out.println(e.toString());
            }
            tbBenhNhan.setModel(new DefaultTableModel(data, columnName));
        } else if (!tfHoTen.getText().equals("") && !tfMaSoBenhNhan.getText().equals("")) {
            String sql = "Select * from \"BenhNhan\" where lower(\"IDBN\")=? and lower(\"Ten\")=?";
            try {
                stmt = con.prepareStatement(sql);
                stmt.setString(1, tfMaSoBenhNhan.getText().toLowerCase().trim());
                stmt.setString(2, tfHoTen.getText().toLowerCase().trim());
                rs = stmt.executeQuery();
                boolean check = false;
                while (rs.next()) {
                    check = true;
                    Vector user = new Vector();
                    user.addElement(rs.getString(1));
                    user.addElement(rs.getString(2));
                    user.addElement(rs.getDate(3));
                    if (rs.getInt(4) == 1) {
                        user.addElement("Nam");
                    } else {
                        user.addElement("Nữ");
                    }

                    user.addElement(rs.getString(5));
                    if (rs.getInt(6) == 1) {
                        user.addElement("Có");
                    } else {
                        user.addElement("Không");
                    }
                    user.addElement(rs.getInt(7));
                    data.add(user);
                }
                if (check == false) {
                    JOptionPane.showMessageDialog(null, "Không tồn tại bệnh nhân. Hãy kiểm tra lại!");
                }
            } catch (Exception e) {
            }
            tbBenhNhan.setModel(new DefaultTableModel(data, columnName));
        } else if (tfHoTen.getText().equals("") && tfMaSoBenhNhan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn hãy nhập mã số bệnh nhân hoặc tên bệnh nhân!");
        }

    }

    private void hienThiTatCa() {
        Vector columnName = new Vector();
        columnName.add("Mã số bệnh nhân");
        columnName.add("Họ và tên");
        columnName.add("Ngày sinh");
        columnName.add("Giới tính");
        columnName.add("Địa chỉ");
        columnName.add("Thẻ bảo hiểm y tế");
        columnName.add("Tuổi");
        Vector data = new Vector();
        String sql = "Select * from \"BenhNhan\" order by \"IDBN\"";
        try {
            stmt = con.prepareStatement(sql);
            rs = stmt.executeQuery();
            while (rs.next()) {
                Vector user = new Vector();
                user.addElement(rs.getString(1));
                user.addElement(rs.getString(2));
                user.addElement(rs.getDate(3));
                if (rs.getInt(4) == 1) {
                    user.addElement("Nam");
                } else {
                    user.addElement("Nữ");
                }

                user.addElement(rs.getString(5));
                if (rs.getInt(6) == 1) {
                    user.addElement("Có");
                } else {
                    user.addElement("Không");
                }
                user.addElement(rs.getInt(7));
                data.add(user);
            }
            tbBenhNhan.setModel(new DefaultTableModel(data, columnName));

        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    private void tfMaSoBenhNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaSoBenhNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaSoBenhNhanActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        showBenhNhan();
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        hienThiTatCa();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (PreObject instanceof QuanLy) {
            ((QuanLy)PreObject).setVisible(true);
        }
        else if(PreObject instanceof SuaBenhNhan){
            ((SuaBenhNhan)PreObject).setVisible(true);
        }
        else if(PreObject instanceof XoaBenhNhan){
            ((XoaBenhNhan)PreObject).setVisible(true);
        }
        else if(PreObject instanceof TinhBenhPhi){
            ((TinhBenhPhi)PreObject).setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimThongTinBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimThongTinBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimThongTinBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimThongTinBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimThongTinBenhNhan("NV0001").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbBenhNhan;
    private javax.swing.JTextField tfHoTen;
    private javax.swing.JTextField tfMaSoBenhNhan;
    // End of variables declaration//GEN-END:variables
}
